# 订阅链接1
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/moneyfly52/Sub/master/sub/share/v2

# 订阅链接2
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/moneyfly52/Sub/master/sub/share/ss

# 订阅链接3
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/moneyfly52/Sub/master/sub/share/ssr

# 订阅链接4
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/moneyfly52/Sub/master/sub/share/tr
